//Will delete later, just to build frontend

const products = [
  {
    id: "1",
    name: "Product 1",
    description: "This is a product",
    newPrice: "₦100",
    oldPrice: "₦1000",
    image: "/Product-pic2.png",
  },
  {
    id: "2",
    name: "Product 2",
    description: "This is a product",
    newPrice: "₦200",
    oldPrice: "₦1000",
    image: "/Product-pic.png",
  },
  {
    id: "3",
    name: "Product 3",
    description: "This is a product",
    newPrice: "₦300",
    oldPrice: "₦1000",
    image: "/Product-pic1.png",
  },
  {
    id: "4",
    name: "Product 4",
    description: "This is a product",
    newPrice: "₦400",
    oldPrice: "₦1000",
    image: "/Product-pic2.png",
  },
  {
    id: "5",
    name: "Product 5",
    description: "This is a product",
    newPrice: "₦500",
    oldPrice: "₦1000",
    image: "/Product-pic1.png",
  },
  {
    id: "6",
    name: "Product 6",
    description: "This is a product",
    newPrice: "₦600",
    oldPrice: "₦1000",
    image: "/Product-pic.png",
  },
  {
    id: "7",
    name: "Product 7",
    description: "This is a product",
    newPrice: "₦700",
    oldPrice: "₦1000",
    image: "/Product-pic2.png",
  },
  {
    id: "8",
    name: "Product 8",
    description: "This is a product",
    newPrice: "₦800",
    oldPrice: "₦1000",
    image: "/Product-pic.png",
  },
  {
    id: "9",
    name: "Product 9",
    description: "This is a product",
    newPrice: "₦900",
    oldPrice: "₦1000",
    image: "/Product-pic.png",
  },
  {
    id: "10",
    name: "Product 10",
    description: "This is a product",
    newPrice: "₦900",
    oldPrice: "₦1000",
    image: "/Product-pic.png",
  },
];

export default products;
